from . import compiled_autograd, eval_frame, guards  # noqa: F401

def strip_function_call(name: str) -> str: ...
def is_valid_var_name(name: str) -> bool | int: ...
def get_type_slots(obj: type | object) -> tuple[int, int, int, int]: ...
